package net.sourceforge.kolmafia.quest

/** Desktop [LatteRequest.LATTE] ingredient table. */
object LatteIngredients {

    data class Entry(
        val ingredient: String,
        val location: String?,
        val first: String,
        val second: String,
        val third: String,
        val modifier: String,
        val discovery: String?,
    )

    val ALL: List<Entry> = listOf(
        Entry("ancient", "The Mouldering Mansion", "Ancient exotic spiced", "ancient/spicy", "with ancient spice", "Spooky Damage: 50", "urn full of ancient spices"),
        Entry("basil", "The Overgrown Lot", "Basil and", "basil", "with basil", "HP Regen Min: 5, HP Regen Max: 5", "clump of wild basil"),
        Entry("belgian", "Whitey's Grove", "Belgian vanilla", "Belgian vanilla", "with a shot of Belgian vanilla", "Muscle Percent: 20, Mysticality Percent: 20, Moxie Percent: 20", "a large vanilla bean pod"),
        Entry("bug-thistle", "The Bugbear Pen", "Bug-thistle", "bug-thistle", "with a sprig of bug-thistle", "Mysticality: 20", "patch of bug-thistle"),
        Entry("butternut", "Madness Bakery", "Butternutty", "butternut-spice", "with butternut", "Spell Damage: 10", "find a butternut squash"),
        Entry("cajun", "The Black Forest", "Cajun", "cajun spice", "with cajun spice", "Meat Drop: 40", "Cayenne you add this to the menu"),
        Entry("carrot", "The Dire Warren", "Carrot", "carrot", "with carrot", "Item Drop: 20", "bunch of carrots"),
        Entry("carrrdamom", "Barrrney's Barrr", "Carrrdamom-scented", "carrrdamom", "with carrrdamom", "MP Regen Min: 4, MP Regen Max: 6", "A carrrdamom"),
        Entry("chalk", "The Haunted Billiards Room", "Blue chalk and", "blue chalk", "with blue chalk", "Cold Damage: 25", "box of blue chalk cubes"),
        Entry("chili", "The Haunted Kitchen", "Chili", "chili seeds", "with a kick", "Hot Resistance: 3", "jar of chili seeds"),
        Entry("cinnamon", null, "Cinna-", "cinnamon", "with a shake of cinnamon", "Experience (Moxie): 1, Moxie Percent: 5, Pickpocket Chance: 5", null),
        Entry("cloves", "The Sleazy Back Alley", "Cloven", "cloves", "with a puff of cloves", "Stench Resistance: 3", "little tin of ground cloves"),
        Entry("coal", "The Haunted Boiler Room", "Coal-boiled", "coal", "with a lump of hot coal", "Hot Damage: 25", "brazier of burning coals"),
        Entry("cocoa", "The Icy Peak", "Cocoa", "cocoa powder", "mocha loca", "Cold Resistance: 3", "packet of cocoa powder"),
        Entry("diet", "Battlefield (No Uniform)", "Diet", "diet soda", "with diet soda syrup", "Initiative: 50", "jug of diet soda syrup"),
        Entry("dwarf", "Itznotyerzitz Mine", "Dwarf creamed", "dwarf cream", "with dwarf cream", "Muscle: 30", "milking a stalactite"),
        Entry("dyspepsi", "Battlefield (Dyspepsi Uniform)", "Dyspepsi-flavored", "Dyspepsi", "with a shot of Dyspepsi syrup", "Initiative: 25", "pure Dyspepsi syrup"),
        Entry("filth", "The Feeding Chamber", "Filthy", "filth milk", "with filth milk", "Damage Reduction: 20", "filth milk"),
        Entry("flour", "The Road to the White Citadel", "Floured", "white flour", "dusted with flour", "Sleaze Resistance: 3", "bag of all-purpose flour"),
        Entry("fungus", "The Fungal Nethers", "Fungal", "fungus", "with fungal scrapings", "Maximum MP: 30", "patch of mushrooms"),
        Entry("grass", "The Hidden Park", "Fresh grass and", "fresh grass", "with fresh-cut grass", "Experience: 3", "pile of fresh lawn clippings"),
        Entry("greasy", "Cobb's Knob Barracks", "Extra-greasy", "hot sausage", "with extra gristle", "Muscle Percent: 50", "big greasy sausage"),
        Entry("greek", "Wartime Frat House (Hippy Disguise)", "Greek spice", "greek spice", "with greek spice", "Sleaze Damage: 25", "ΣΠΙΣΗΣ"),
        Entry("grobold", "The Old Rubee Mine", "Grobold rum and", "grobold rum", "with a shot of grobold rum", "Sleaze Damage: 25", "stash of grobold rum"),
        Entry("guarna", "The Bat Hole Entrance", "Guarna and", "guarna", "infused with guarna", "Adventures: 4", "patch of guarana plants"),
        Entry("gunpowder", "1st Floor, Shiawase-Mitsuhama Building", "Gunpowder and", "gunpowder", "with gunpowder", "Weapon Damage: 50", "jar of gunpowder"),
        Entry("healing", "The Daily Dungeon", "Extra-healthy", "health potion", "with a shot of healing elixir", "HP Regen Min: 10, HP Regen Max: 20", "jug full of red syrup"),
        Entry("hellion", "The Dark Neck of the Woods", "Hellish", "hellion", "with hellion", "PvP Fights: 6", "small pile of hellion cubes"),
        Entry("hobo", "Hobopolis Town Square", "Hobo-spiced", "hobo spice", "with hobo spice", "Damage Absorption: 50", "Hobo Spices"),
        Entry("ink", "The Haunted Library", "Inky", "ink", "with ink", "Combat Rate: -10", "large bottle of india ink"),
        Entry("kombucha", "Wartime Hippy Camp (Frat Disguise)", "Kombucha-infused", "kombucha", "with a kombucha chaser", "Stench Damage: 25", "bottle of homemade kombucha"),
        Entry("lihc", "The Defiled Niche", "Lihc-licked", "lihc saliva", "with lihc spit", "Spooky Damage: 25", "collect some of the saliva in a jar"),
        Entry("lizard", "The Arid, Extra-Dry Desert", "Lizard milk and", "lizard milk", "with lizard milk", "MP Regen Min: 5, MP Regen Max: 15", "must be lizard milk"),
        Entry("mega", "Cobb's Knob Laboratory", "Super-greasy", "mega sausage", "with super gristle", "Moxie Percent: 50", "biggest sausage you've ever seen"),
        Entry("mold", "The Unquiet Garves", "Moldy", "grave mold", "with grave mold", "Spooky Damage: 20", "covered with mold"),
        Entry("msg", "The Briniest Deepests", "MSG-Laced", "MSG", "with flavor", "Critical Hit Percent: 15", "pure MSG from the ocean"),
        Entry("noodles", "The Haunted Pantry", "Carb-loaded", "macaroni", "with extra noodles", "Maximum HP: 20", "espresso-grade noodles"),
        Entry("norwhal", "The Ice Hole", "Norwhal milk and", "norwhal milk", "with norwhal milk", "Maximum HP Percent: 200", "especially Nordic flavor to it"),
        Entry("oil", "The Old Landfill", "Motor oil and", "motor oil", "with motor oil", "Sleaze Damage: 20", "puddle of old motor oil"),
        Entry("paint", "The Haunted Gallery", "Oil-paint and", "oil paint", "with oil paint", "Cold Damage: 5, Hot Damage: 5, Sleaze Damage: 5, Spooky Damage: 5, Stench Damage: 5", "large painter's pallette"),
        Entry("paradise", "The Stately Pleasure Dome", "Paradise milk", "paradise milk", "with milk of paradise", "Muscle: 20, Mysticality: 20, Moxie: 20", "Milk of Paradise"),
        Entry("pumpkin", null, "Autumnal", "pumpkin spice", "with a hint of autumn", "Experience (Mysticality): 1, Mysticality Percent: 5, Spell Damage: 5", null),
        Entry("rawhide", "The Spooky Forest", "Rawhide", "rawhide", "with rawhide", "Familiar Weight: 5", "stash of rawhide dog chews"),
        Entry("rock", "The Brinier Deepers", "Extra-salty", "rock salt", "with rock salt", "Critical Hit Percent: 10", "large salt deposits"),
        Entry("salt", "The Briny Deeps", "Salted", "salt", "with salt", "Critical Hit Percent: 5", "distill some of the salt"),
        Entry("sandalwood", "Noob Cave", "Sandalwood-infused", "sandalwood splinter", "with sandalwood splinters", "Muscle: 5, Mysticality: 5, Moxie: 5", "made of sandalwood"),
        Entry("sausage", "Cobb's Knob Kitchens", "Greasy", "sausage", "with gristle", "Mysticality Percent: 50", "full of sausages"),
        Entry("space", "The Hole in the Sky", "Space pumpkin and", "space pumpkin", "with space pumpkin juice", "Muscle: 10, Mysticality: 10, Moxie: 10", "some kind of brown powder"),
        Entry("squamous", "The Caliginous Abyss", "Squamous-salted", "squamous", "with squamous salt", "Spooky Resistance: 3", "break off a shard"),
        Entry("squash", "The Copperhead Club", "Spaghetti-squashy", "spaghetti squash spice", "with extra squash", "Spell Damage: 20", "steal a spaghetti squash"),
        Entry("teeth", "The VERY Unquiet Garves", "Teeth", "teeth", "with teeth in it", "Spooky Damage: 25, Weapon Damage: 25", "handful of loose teeth"),
        Entry("vanilla", null, "Vanilla", "vanilla", "with a shot of vanilla", "Experience (Muscle): 1, Muscle Percent: 5, Weapon Damage Percent: 5", null),
        Entry("venom", "The Middle Chamber", "Envenomed", "asp venom", "with extra poison", "Weapon Damage: 25", "wring the poison out of it into a jar"),
        Entry("vitamins", "The Dark Elbow of the Woods", "Fortified", "vitamin", "enriched with vitamins", "Experience (familiar): 3", "specifically vitamins G, L, P, and W"),
        Entry("wing", "The Dark Heart of the Woods", "Hot wing and", "hot wing", "with a hot wing in it", "Combat Rate: 10", "plate of hot wings"),
    )

    fun byFirst(description: String): Entry? = ALL.firstOrNull { it.first == description }
}
