package net.sourceforge.kolmafia.quest

enum class Quest(val prefKey: String) {
    // ── Council quests ────────────────────────────────────────────────────────
    LARVA("questL02Larva"),
    RAT("questL03Rat"),
    BAT("questL04Bat"),
    GOBLIN("questL05Goblin"),
    FRIAR("questL06Friar"),
    CYRPT("questL07Cyrptic"),
    TRAPPER("questL08Trapper"),
    TOPPING("questL09Topping"),
    GARBAGE("questL10Garbage"),
    MACGUFFIN("questL11MacGuffin"),
    BLACK("questL11Black"),
    WORSHIP("questL11Worship"),
    MANOR("questL11Manor"),
    PYRAMID("questL11Pyramid"),
    PALINDOME("questL11Palindome"),
    SHEN("questL11Shen"),
    RON("questL11Ron"),
    CURSES("questL11Curses"),
    DOCTOR("questL11Doctor"),
    BUSINESS("questL11Business"),
    SPARE("questL11Spare"),
    DESERT("questL11Desert"),
    ISLAND_WAR("questL12War"),
    HIPPY_FRAT("questL12HippyFrat"),
    FINAL("questL13Final"),
    WAREHOUSE("questL13Warehouse"),

    // ── Guild quests ──────────────────────────────────────────────────────────
    MEATCAR("questG01Meatcar"),
    CITADEL("questG02Whitecastle"),
    EGO("questG03Ego"),
    NEMESIS("questG04Nemesis"),
    DARK("questG05Dark"),
    FACTORY("questG06Delivery"),
    MYST("questG07Myst"),
    MOXIE("questG08Moxie"),
    MUSCLE("questG09Muscle"),

    // ── Miscellaneous quests ──────────────────────────────────────────────────
    UNTINKER("questM01Untinker"),
    ARTIST("questM02Artist"),
    BUGBEAR("questM03Bugbear"),
    TOOT("questM05Toot"),
    HAMMER("questM07Hammer"),
    BAKER("questM08Baker"),
    AZAZEL("questM10Azazel"),
    PIRATE("questM12Pirate"),
    ESCAPE("questM13Escape"),
    LOL("questM15Lol"),
    TEMPLE("questM16Temple"),
    SPOOKYRAVEN_BABIES("questM17Babies"),
    SWAMP("questM18Swamp"),
    HIPPY("questM19Hippy"),
    SPOOKYRAVEN_NECKLACE("questM20Necklace"),
    SPOOKYRAVEN_DANCE("questM21Dance"),
    SHIRT("questM22Shirt"),
    MEATSMITH("questM23Meatsmith"),
    DOC("questM24Doc"),
    ARMORER("questM25Armorer"),
    ORACLE("questM26Oracle"),

    // ── Future / Sea quests ───────────────────────────────────────────────────
    PRIMORDIAL("questF01Primordial"),
    FUTURE("questF03Future"),
    GENERATOR("questF04Elves"),
    CLANCY("questF05Clancy"),
    SEA_OLD_GUY("questS01OldGuy"),
    SEA_MONKEES("questS02Monkees"),

    // ── Spookyraven sub-quests ────────────────────────────────────────────────
    JIMMY_MUSHROOM("questESlMushStash"),
    JIMMY_CHEESEBURGER("questESlCheeseburger"),
    JIMMY_SALT("questESlSalt"),
    TACO_DAN_AUDIT("questESlAudit"),
    TACO_DAN_COCKTAIL("questESlCocktail"),
    TACO_DAN_FISH("questESlFish"),
    BRODEN_BACTERIA("questESlBacteria"),
    BRODEN_SPRINKLES("questESlSprinkles"),
    BRODEN_DEBT("questESlDebt"),

    // ── Special event quests ──────────────────────────────────────────────────
    EVE("questESpEVE"),
    JUNGLE_PUN("questESpJunglePun"),
    GORE("questESpGore"),
    CLIPPER("questESpClipper"),
    FAKE_MEDIUM("questESpFakeMedium"),
    SERUM("questESpSerum"),
    SMOKES("questESpSmokes"),
    OUT_OF_ORDER("questESpOutOfOrder"),

    // ── Standard event quests ─────────────────────────────────────────────────
    FISH_TRASH("questEStFishTrash"),
    GIVE_ME_FUEL("questEStGiveMeFuel"),
    NASTY_BEARS("questEStNastyBears"),
    SOCIAL_JUSTICE_I("questEStSocialJusticeI"),
    SOCIAL_JUSTICE_II("questEStSocialJusticeII"),
    SUPER_LUBER("questEStSuperLuber"),
    WORK_WITH_FOOD("questEStWorkWithFood"),
    ZIPPITY_DOO_DAH("questEStZippityDooDah"),

    // ── Community / one-off quests ────────────────────────────────────────────
    BUCKET("questECoBucket"),
    TELEGRAM("questLTTQuestByWire"),
    GHOST("questPAGhost"),
    NEW_YOU("questEUNewYou"),
    PARTY_FAIR("_questPartyFair"),
    DOCTOR_BAG("questDoctorBag"),
    GUZZLR("questGuzzlr"),
    CLUMSINESS("questClumsinessGrove"),
    MAELSTROM("questMaelstromOfLovers"),
    GLACIER("questGlacierOfJerks"),
    RUFUS("questRufus"),
    PIRATEREALM("_questPirateRealm"),
}
